### ISSUE TITLE
#[derive(Deserialize)] macro cannot create expander UnsupportetABI

### ISSUE THREAD

**Issue by romanstingler** [lapce/lapce-rust#17]
![image](https://user-images.githubusercontent.com/5576250/206871764-3b53cbe2-72c5-4f47-abc7-3f53b7fc2b24.png)

I just started learning Rust, so I am not confident that this is a bug but
why does
```#[derive(Deserialize)]```
throw this error?
In Sublime, it is not shown.

**Comment by semenInRussia** [comment]
Try run `cargo build` using command line
