### ISSUE TITLE
No option to exclude specific projects

### ISSUE THREAD

**Issue by Max7cd** [lapce/lapce-rust#19]
rust-analyzer in VSCode allows me to specify directories to be excluded during indexing using the setting: `rust-analyzer.files.excludeDirs`
lapce-rust currently lacks this setting.

I have one project, which will always fail compilation in a default environment. If this directory is not excluded specifically, the extension will not start up correctly and all the other projects in the workspace will not get LSP features.

**Comment by panekj** [comment]
You can set `lapce-rust.configuration.files.excludeDirs`

**Comment by Max7cd** [comment]
Interesting...
Are all of the settings the VSCode plugin offers also available using these configuration strings?
Is there a documentation of the supported ones?
I was just confused, since there were almost no settings available in the UI.
Thanks a lot :)

**Comment by panekj** [comment]
> Is there a documentation of the supported ones?

https://rust-analyzer.github.io/manual.html#configuration

> Are all of the settings the VSCode plugin offers also available using these configuration strings?

Everything that rust-analyzer provides is available.
