### ISSUE TITLE
plugin rust set RA path turn on error

### ISSUE THREAD

**Issue by zhouxs1023** [lapce/lapce-rust#26]
os: windows 10
RA path C:\Users\Administrator\.vscode\extensions\rust-lang.rust-analyzer-0.3.1435-win32-x64\server\rust-analyzer.exe

lapce rust plugin server path set as below:
![rust set](https://user-images.githubusercontent.com/905931/227253697-868e05a0-f5ea-4fe3-8fd9-2c2112255831.PNG)

open rust project turn error as below:
![rust-plugin error](https://user-images.githubusercontent.com/905931/227253922-73fb73d8-6b8f-461a-b0f3-7232dc96c9c0.PNG)

**Comment by catb0t** [comment]
Even though it is called "path" the value is passed to `where` on Windows 

so we have to provide a non-absolute path resolvable by `where`

https://github.com/lapce/lapce-rust/blob/02d3a760137caf815f6c028b738f5ad58bf3c58a/src/main.rs#L47-L61

my solution was to have `~/bin` in my PATH already, and then:
```cmd
> mklink C:\users\%USERNAME%\bin\win-nightly-rust-analyzer.exe C:\Users\%USERNAME%\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\rust-analyzer.exe
symbolic link created for ....

> where win-nightly-rust-analyzer.exe
C:\Users\%USERNAME%\bin\win-nightly-rust-analyzer.exe
```

then put `win-nightly-rust-analyzer.exe` as the "Server path" in the plugin settings for now

**Comment by zhouxs1023** [comment]
Cat Stevens, Thanks you very much, The problem has already been solved.
