### ISSUE TITLE
Allow easier analyzer configuration

### ISSUE THREAD

**Issue by TheIronBorn** [lapce/lapce-rust#28]
At least allowing the user to manually set some config json per https://rust-analyzer.github.io/manual.html#configuration would be nice

**Comment by panekj** [comment]
You can already do that via settings file

**Comment by TheIronBorn** [comment]
Can you provide an example? I tried several methods in https://github.com/lapce/lapce/issues/180 but none seemed to work

**Comment by TheIronBorn** [comment]
For posterity, I was able to change `RUSTFLAGS` with 
```toml
[lapce-rust]
"server.extraEnv.RUSTFLAGS" = "arg1 arg2"
```
in `.../AppData/Roaming/lapce/Lapce-Stable/config/settings.toml`
