### ISSUE TITLE
serverPath setting not respected/working

### ISSUE THREAD

**Issue by ShyOnyx** [lapce/lapce-rust#32]
I'm getting the `proc macro not expanded: Proc-macro dylib loading failed: unsupported metadata version 7` error.

I've tried installing rust-analyzer via pacman and setting [config.serverPath] in volt.toml to `default = "/usr/bin/rust-analyzer"`, but that either doesn't actually do anything, or is somehow not checking the correct path.

I've also tried renaming rust-analyzer in /usr/bin to rust-analyzer-x86_64-unknown-linux-gnu, did not work.

Temporary solution:

Copy rust-analyzer from /usr/bin to lapce-rust directory and rename to rust-analyzer-x86_64-unknown-linux-gnu.

**Comment by sanjeevprasad** [comment]
Open Settings (Ctrl + .)
goto "Plugin Settings" > "Rust"
Change "Server Path" to "/usr/bin/rust-analyzer"
or whatever it is in your case.

This is a temporary/permanent workaround

**Comment by romancitodev** [comment]
In windows doesn't work.

**Comment by ShyOnyx** [comment]
That works! I was using an outdated fix, I apologize.

This issue is solved. Thank you!
