### ISSUE TITLE
Cannot specify path to rust-analyzer on windows

### ISSUE THREAD

**Issue by toadslop** [lapce/lapce-rust#34]
This line always results in an error on windows, making it impossible to specify the path to rust-analyzer.

```
let exits = PLUGIN_RPC
            .execute_process(program.to_string(), vec![server_path.to_string()])
            .map(|r| r.success)
            .unwrap_or(false);
```

Looking at the sourceode, it executes the program "where" with the path you provide. This *does not work*. Here is an example of the output:

```cmd
where C:\Users\bnhei\.cargo\bin\rust-analyzer.exe
ERROR: Invalid pattern is specified in "path:pattern".
```

As we can see, we cannot simply input the path to rust analyzer with the `where` command. It will always fail. The correct format for this command is: `{path-to-folder}:{filename-pattern-matcher}`.

**Comment by eckce** [comment]
Same issue on Linux. Using lapce nightly. Rust plugin installed via lapce UI.

![image](https://github.com/lapce/lapce-rust/assets/129222600/9d57f53f-6c78-4aab-bf4a-2e542f207eb9)
![image](https://github.com/lapce/lapce-rust/assets/129222600/8632c0a9-23df-4fa3-9676-c482f7613834)
![image](https://github.com/lapce/lapce-rust/assets/129222600/d19e9e98-51ed-46b1-9969-76b6c66238b0)

**Comment by humphreylee** [comment]
bumped.
