### ISSUE TITLE
Crash when U+250C is in a comment block

### ISSUE THREAD

**Issue by ghost** [lapce/lapce-rust#7]
The crash only happens with the rust plugin installed so I figured I would open the issue here.

Opening [this](https://github.com/tokio-rs/bytes/blob/master/src/bytes.rs#L90) file from the [bytes crate](https://crates.io/crates/bytes) causes my lapce editor to crash.

It seems to be caused by the character `┌` (U+250C) being in a comment block as I can paste the character outside of a comment without it crashing.

Tested on MacOS version 12.5 and Windows 11 version 21H2

Lapce version: 0.1.3

**Comment by MinusGix** [comment]
This is probably fixed on the master branch of Lapce (so it should be fixed on the nightly, and when we make another release). There was issues with the encoding used by the LSP (UTF16) and the encoding used by Lapce internally (UTF8).

**Comment by ghost** [comment]
> This is probably fixed on the master branch of Lapce (so it should be fixed on the nightly, and when we make another release). There was issues with the encoding used by the LSP (UTF16) and the encoding used by Lapce internally (UTF8).

From what I can tell it is fixed in the master branch! Thank you very much.
